name: Build AOC Container Images

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  #################################################################################################

  prepare:
    runs-on: [lcas, qemu]
    outputs:
      image_context: ${{ steps.vars.outputs.image_context }}
    steps:
      # Work out the context of this build request, store as an output!
      - id: vars
        run: |
          if [ "${GITHUB_EVENT_NAME}" = "pull_request" ]; then
            IMAGE_CONTEXT="staging"
          elif [ "${GITHUB_REF_TYPE}" = "tag" ]; then
            IMAGE_CONTEXT="${GITHUB_REF_NAME}"
          elif [ "${GITHUB_REF_NAME}" = "main" ]; then
            IMAGE_CONTEXT="main"
          else
            IMAGE_CONTEXT="staging"
          fi

          echo "image_context=${IMAGE_CONTEXT}" >> "$GITHUB_OUTPUT"

  #################################################################################################
  build_standalone:
    name: Build ${{ matrix.push_image }}
    needs: prepare
    strategy:
      matrix:
        include:
          # VNC standalone image
          - base_image: "debian:trixie-slim"
            push_image: "vnc"
            dockerfile: "vnc.dockerfile"
            architectures: "linux/amd64,linux/arm64"

    uses: ./.github/workflows/_build-standalone-image.yaml
    with:
      base_image: ${{ matrix.base_image }}
      push_image: ${{ matrix.push_image }}
      dockerfile: ${{ matrix.dockerfile }}
      architectures: ${{ matrix.architectures }}
    secrets: inherit
    

  build_ros:
    name: Build ${{ matrix.push_image }} ${{ matrix.tag_stem }}
    needs: prepare
    strategy:
      max-parallel: 8
      matrix:
        include:
          # ROS Humble
          - base_image: "ros:humble"
            push_image: "ros"
            ros_distro: "humble"
            tag_stem: "humble"
            dockerfile: "base.dockerfile"
            architectures: "linux/amd64,linux/arm64"

          # ROS Jazzy
          - base_image: "ros:jazzy"
            push_image: "ros"
            ros_distro: "jazzy"
            tag_stem: "jazzy"
            dockerfile: "base.dockerfile"
            architectures: "linux/amd64,linux/arm64"

          # ROS CUDA Humble
          - base_image: "nvidia/cuda:11.8.0-runtime-ubuntu22.04"
            push_image: "ros_cuda"
            ros_distro: "humble"
            tag_stem: "humble-11.8"
            dockerfile: "cuda.dockerfile"
            architectures: "linux/amd64"
            build_desktop: true
            desktop_push_image: "ros_cuda_desktop"

          # ROS CUDA Jazzy
          - base_image: "nvidia/cuda:12.9.1-runtime-ubuntu24.04"
            push_image: "ros_cuda"
            ros_distro: "jazzy"
            tag_stem: "jazzy-12.9"
            dockerfile: "cuda.dockerfile"
            architectures: "linux/amd64"
            build_desktop: true
            desktop_push_image: "ros_cuda_desktop"

    uses: ./.github/workflows/_build-ros-image.yaml
    with:
      base_image: ${{ matrix.base_image }}
      push_image: ${{ matrix.push_image }}
      tag_stem: ${{ matrix.tag_stem }}
      image_context: ${{ needs.prepare.outputs.image_context }}
      ros_distro: ${{ matrix.ros_distro }}
      dockerfile: ${{ matrix.dockerfile }}
      architectures: ${{ matrix.architectures }}
      build_desktop: ${{ matrix.build_desktop || false }}
      desktop_push_image: ${{ matrix.desktop_push_image }}
    secrets: inherit
